# Generated by Django 5.2.1 on 2025-07-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_producto_proveedor_producto_medicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo_medida',
        ),
    ]
