# Generated by Django 5.2.1 on 2025-07-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_producto_tipo_medida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='medicion',
            new_name='medida',
        ),
    ]
