# Generated by Django 5.2.1 on 2025-08-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_producto_stock'),
        ('api', '0010_remove_movimiento_venta_movimiento_fecha_and_more'),
    ]

    operations = [
    ]
