# Generated by Django 5.2.1 on 2025-09-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20250825_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje sobre el total'), ('PRECIO_FIJO', 'Precio fijo por combo'), ('CANTIDAD', 'Ej: 2x1, 3x2')], max_length=20)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precio_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_requerida', models.PositiveIntegerField(blank=True, null=True)),
                ('cantidad_pagada', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('productos', models.ManyToManyField(related_name='descuentos', to='api.producto')),
            ],
        ),
    ]
