# Generated by Django 5.2.1 on 2025-09-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_movimiento_total_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuento',
            name='productos',
        ),
        migrations.CreateModel(
            name='ProductoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.descuento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
        ),
    ]
