# Generated by Django 5.2.1 on 2025-09-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_descuento_productos_productodescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='productos',
            field=models.ManyToManyField(related_name='descuentos', through='api.ProductoDescuento', to='api.producto'),
        ),
    ]
