# Generated by Django 5.2.1 on 2025-12-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movimiento_cantidad_alter_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='min_unidades',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='tipo',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('PRECIO_FIJO', 'Combo precio fijo'), ('CANTIDAD', '2x1 / 3x2'), ('MAYORISTA', 'Mayorista por unidades')], max_length=20),
        ),
    ]
